### PR TITLE
(feat): Adding flexbox classes.

### PR DESCRIPTION
**Pull request by thisduck**
This PR adds flexbox based classes as supported.

### CODE REVIEW

**Comment by rigor789** [comment]
Nice! 
Is it ready to merge down to the tw2 branch?

**Comment by thisduck** [comment]
@rigor789 Yes! I've been using this branch in an app for work.

I also fixed the `main` setting in package.json from when I added the animation options. So now it works properly when integrating via postcss.
I didn't get a chance to test out the animation at that point. So this PR has fixes for that.
Unfortunately not all animations work `animate-bounce` is the only one that works nicely. I think it might be because of a bug in Nativescript, but not 100% sure.

**Comment by rigor789** [comment]
Great! It's likely a bug in NS - can investigate that later, not a huge deal at this point I'd say!

**Comment by thisduck** [comment]
@rigor789 Just for completeness, for something like spinning. Tailwind has:

```
@keyframes spin {
  to {
    transform: rotate(360deg)
  }
}
```

This works fine in the browser. But in NS, it doesn't work unless the `from` keyframe is added as well. When iteration is infinite, animate-bounce works fine, but spin only spins twice (or so) and stops.

**Pull request merged**
